/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.example.android.documentcentricapps;

public final class R {
    public static final class attr {
    }
    public static final class dimen {
        /**  Default screen margins, per the Android Design guidelines. 
         */
        public static final int activity_horizontal_margin=0x7f060000;
        public static final int activity_vertical_margin=0x7f060001;
        /**  Semantic definitions 
 Semantic definitions 
         */
        public static final int horizontal_page_margin=0x7f060007;
        public static final int margin_huge=0x7f060006;
        public static final int margin_large=0x7f060005;
        public static final int margin_medium=0x7f060004;
        public static final int margin_small=0x7f060003;
        /**  Define standard dimensions to comply with Holo-style grids and rhythm. 
         */
        public static final int margin_tiny=0x7f060002;
        public static final int vertical_page_margin=0x7f060008;
    }
    public static final class drawable {
        public static final int ic_launcher=0x7f020000;
        public static final int tile=0x7f020001;
    }
    public static final class id {
        public static final int hello_new_document_text_view=0x7f070002;
        public static final int multiple_task_checkbox=0x7f070001;
        public static final int new_document_button=0x7f070000;
        public static final int remove_task_button=0x7f070003;
    }
    public static final class layout {
        public static final int activity_document_centric_main=0x7f030000;
        public static final int activity_new_document=0x7f030001;
    }
    public static final class string {
        public static final int activity_new_document_title=0x7f040005;
        public static final int app_name=0x7f040000;
        public static final int hello_new_document_counter=0x7f040003;
        public static final int intro_message=0x7f040001;
        public static final int multiple_task_checkbox_label=0x7f040007;
        public static final int new_document_button_text=0x7f040006;
        public static final int remove_task_button_text=0x7f040008;
        public static final int reusing_document_counter=0x7f040004;
        public static final int title_activity_main=0x7f040002;
    }
    public static final class style {
        public static final int AppTheme=0x7f050002;
        /**  Activity themes 
 Activity themes 
 Activity themes 
         */
        public static final int Theme_Base=0x7f050000;
        public static final int Theme_Sample=0x7f050001;
        /**  Widget styling 
         */
        public static final int Widget=0x7f050003;
        public static final int Widget_SampleMessage=0x7f050004;
        public static final int Widget_SampleMessageTile=0x7f050005;
    }
}
